tooling_dir: tooling

pod5_dir: datasets/pod5

exps: [Ecoli_WT, Ecoli_DM, Ecoli_DM_MSssI , HP26695_WT, HP26695_WGA, Tdenticola_NAT, Nostoc_NAT, HPJ99_NAT]
runs: []
acc:  [sup,hac]

dorado_mods:
  5mC:  [v4r1, v5r1, v5r3, v5.2r2]
  5mCG: [v4r1, v5r1, v5r3, v5.2r2]
  6mA:  [v4r1, v4r2, v5r1, v5r3, v5.2r1]
  4mC:  [v4r1, v5r1, v5r3, v5.2r1]

rockfish_run:             []
deepmod2_transformer_run: [v5r3]
deepmod2_bilstm_run:      [v5r3]
f5c_run:                  []
f5c_stranded_run:         []
deepbam_run:              []
deepplnat_run:             []

# TOOLING CONFIG
# ----------------------------------------------------------------------
# models:
RERIO_MODELS: /data1/tools/rerio/dorado_models
DORADO_MODELS: /data1/tools/doradomodels

tooling_dir: "tooling"

tooling:
  bedtools: bedtools
  samtools: samtools
  modkit:   /data1/tools/modkit/modkit
  dorado:
    install: dorado
    model_dir: dorado_models
    minQscore: 10
    platform: linux-x64
    dorado_version: 
      4kHz_v4:   dorado-0.5.3
      5kHz_v4:   dorado-0.9.1
      5kHz_v5:   dorado-0.9.1
      5kHz_v5.2: dorado-1.1.1
    dorado_version_names: 
      dorado-0.5.3: dorado053
      dorado-0.9.1: dorado091
      dorado-1.1.1: dorado111
  deepmod2: 
    install: deepmod2
    execut: deepmod2
    conda: deepmod2_test
    cuda: 12.8
  rockfish: 
    install: rockfish
    model: /data1/tools/rockfishmodels/rf_5kHz.ckpt
    conda: rockfish_test
  f5c:
    install: f5c-v1.5
    execut:  f5c_x86_64_linux_cuda
    version: 1.5
  deepplant: 
    install: /data1/tools/DeepPlant
    execut:  /data1/tools/DeepPlant/build/DeepPlant
    model:   /data1/tools/DeepPlant/model/bilstm/
    conda:   deepplant
  deepbam: 
    install: /data1/tools/DeepBAM
    execut:  /data1/tools/DeepBAM/cpp/build/DeepBAM
    model:   /data1/tools/DeepBAM/traced_script_module/LSTM_20240524_newfeature_script_b9_s15_epoch25_accuracy0.9742.pt
    conda:   DeepBAM

dorado_config:
  4kHz_v4r1:   dorado-v0.5.3
  4kHz_v4r2:   dorado-v0.5.3
  5kHz_v4r1:   dorado-v0.9.1
  5kHz_v4r2:   dorado-v0.9.1
  5kHz_v5r1:   dorado-v0.9.1
  5kHz_v5r2:   dorado-v0.9.1
  5kHz_v5r3:   dorado-v0.9.1
  5kHz_v5.2r1: dorado-v1.1.1
  5kHz_v5.2r2: dorado-v1.1.1

version_model_lookup:
  4kHz: [v4r2]
  5kHz: [v4r1, v4r2, v5r1, v5r2, v5r3, v5.2r1, v5.2r2]

CONDA_ENVS:
  rockfish: rockfish_test

## LOG 
timit: True
logit: True